version: "3.7"
services:
  nginx:
    container_name: holeinone_server
    image: nginx:1.15
    ports:
      - 15101:80
    networks:
      - holeinone-network
    volumes:
      - "../server_configs/server_nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: holeinone_frontend
    image: "${DOCKER_USER}/holeinone_frontend"
    command: "npm run start"
    environment:
      REACT_APP_AUTH_KEY: ${APP_AUTH_KEY}
    tty: true
    networks:
      holeinone-network:

  backend:
    container_name: holeinone_backend
    image: ${DOCKER_USER}/holeinone_backend
    command: "npm run start"
    environment:
      DB_HOSTNAME: "${DATABASE_HOST}"
      DB_DATABASE: "${DATABASE_NAME}"
      DB_USERNAME: "${DATABASE_USER}"
      DB_PASSWORD: "${DATABASE_PASS}"
    networks:
      holeinone-network:

  mongodb:
    container_name: holeinone_db
    image: "${DOCKER_USER}/holeinone_db"
    restart: unless-stopped
    volumes:
      - mongodbdata:/docker-entrypoint-initdb.d/
      - mongodbdata:/data/configdb/
      - mongodbdata:/data/db/
    networks:
      holeinone-network:

networks:
  holeinone-network:
volumes:
  mongodbdata:
    driver: local
