name: holeinone_image_pusher

# Trigger settings
on:
  push:
    branches: [main]

# Environment variables
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

# Jobs
jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      # Before action : checkout source code
      - uses: actions/checkout@v2
      # 1. Docker login using username and password
      - name: docker login
        run: |
          echo "================ Docker Login ================"
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          echo "============ Docker Login SUCCESS ============"
      # 2. Write environment file
      - name: "Create and write environment file"
        run: |
          cd ./deployment
          echo "DOCKER_USER=${{secret.DOCKER_USER}}" >> .env
          echo "DATABASE_NAME=${{secret.DB_NAME}}" >> .env
          echo "DATABASE_USER=${{secret.DB_USER}}" >> .env
          echo "DATABASE_PASS=${{secret.DB_PASS}}" >> .env
          echo "MONGO_INIT_USER=${{secret.DB_INIT_USER}}" >> .env
          echo "MONGO_INIT_PASS=${{secret.DB_INIT_PASS}}" >> .env
      # 2. Build using docker-compose file
      - name: Build the Docker image
        working-directory: ./deployment
        run: |
          echo "================ Build image ================"
          docker-compose -f build-dockercompose.yml --env-file .env build
          echo "============ Build image SUCCESS ============"
      # 3. Push to dockerhub
      - name: Docker Push
        working-directory: ./deployment
        run: |
          echo "================ Push image ================"
          docker-compose -f build-dockercompose.yml push
          echo "=========== Push image SUCCESS ============="
